version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: timesheet-devops-db
    ports:
      - "3306:3306"
    volumes:
      - timesheetvol:/var/lib/mysql

  timesheet:
    image: timesheet-rouaalaabidi-2alinfo1
    container_name: timesheet-app
    depends_on:
      - mysqldb
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timesheet-devops-db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123

volumes:
  timesheetvol:
